// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVzBE87O_iWfppC1sU-ClH_cMY89w_1Mc',
    appId: '1:267015950939:web:6459a2b096339e46dea57e',
    messagingSenderId: '267015950939',
    projectId: 'muktobarta-b02e8',
    authDomain: 'muktobarta-b02e8.firebaseapp.com',
    storageBucket: 'muktobarta-b02e8.firebasestorage.app',
    measurementId: 'G-R3XHHEGDDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwjBaXjLblIG6H7Q2ChaMLBcXCRmtDEa8',
    appId: '1:267015950939:android:fd8992905a5dd72ddea57e',
    messagingSenderId: '267015950939',
    projectId: 'muktobarta-b02e8',
    storageBucket: 'muktobarta-b02e8.firebasestorage.app',
  );
}
